-- Localized representative job titles generated by the server-side crawler.

ALTER TABLE jobs
  ADD COLUMN IF NOT EXISTS title_translations JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE jobs
  DROP CONSTRAINT IF EXISTS jobs_title_translations_object_check;

ALTER TABLE jobs
  ADD CONSTRAINT jobs_title_translations_object_check
  CHECK (jsonb_typeof(title_translations) = 'object');

CREATE INDEX IF NOT EXISTS jobs_missing_title_translations_idx
  ON jobs (updated_at DESC)
  WHERE title IS NOT NULL
    AND title <> ''
    AND NOT (title_translations ?& ARRAY['ko', 'en', 'ja', 'zh']);
